services:
  frontend:
    build: 
      context: ./frontend/fitgym
      dockerfile: frontend.Dockerfile
    depends_on:
      - nginx
    volumes:
      - web-build:/app/build/web
    networks:
      - app-network

  backend:
    env_file:
      - ./backend/.env
    build:
      context: ./
      dockerfile: ./backend/backend.Dockerfile
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy 
    networks:
      - app-network
    
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - web-build:/usr/share/nginx/html:ro
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network


  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d fitgym"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network


volumes:
  db-data:
  web-build:
networks:
  app-network:
    driver: bridge