services:

  # Backend Service soon...

  # Frontend Service soon...

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fitgym
      POSTGRES_HOST: postgres
    restart: unless-stopped
    volumes:
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
volumes:
  db-data:

networks:
  app-network:
    driver: bridge