services:
  frontend:
    build: 
      context: ./frontend/fitgym
      dockerfile: Dockerfile
    # depends_on:
    #   - backend
    volumes:
      - web-build:/app/build/web
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    networks:
      - app-network
    
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - web-build:/usr/share/nginx/html:ro
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network


  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fitgym
      POSTGRES_HOST: postgres
    volumes:
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network


volumes:
# db-data:
  web-build:
networks:
  app-network:
    driver: bridge